name = "season-6-modpack"
mc_version = "1.20.1"

[jar]
type = "quilt"
loader = "0.23.0-beta.1"
installer = "latest"

[variables]
PORT = "25565"

[launcher]
eula_args = true
nogui = true

[[mods]]
type = "modrinth"
id = "5ZwdcRci"
version = "3EgIBnht"

[[mods]]
type = "modrinth"
id = "Xbc0uyRg"
version = "qlA1WuOK"

[[mods]]
type = "modrinth"
id = "lfHFW1mp"
version = "jEeKb7lx"

[[mods]]
type = "modrinth"
id = "fRiHVvU7"
version = "X6In4fQO"

[[mods]]
type = "modrinth"
id = "aXf2OSFU"
version = "buDX2XKX"

[[mods]]
type = "modrinth"
id = "mfzaZK3Z"
version = "Lr5BTYBp"

[[mods]]
type = "modrinth"
id = "u5Ic2U1u"
version = "wPtDzPBH"

[[mods]]
type = "modrinth"
id = "QwxR6Gcd"
version = "6XDJoCks"

[[mods]]
type = "modrinth"
id = "wbWoo11W"
version = "EQYdSyh8"

[[mods]]
type = "modrinth"
id = "qbbO7Jns"
version = "7fjkgVEh"

[[mods]]
type = "modrinth"
id = "2RKFTmiB"
version = "B2L4LeMV"

[[mods]]
type = "modrinth"
id = "AANobbMI"
version = "vgceLbdH"

[[mods]]
type = "modrinth"
id = "5aaWibi9"
version = "e563ycts"

[[mods]]
type = "modrinth"
id = "L7Du7ajc"
version = "I38hyWv7"

[[mods]]
type = "modrinth"
id = "jTUiUpsh"
version = "fQQ8wvKT"

[[mods]]
type = "modrinth"
id = "nDHcEOt3"
version = "Jm5dnfOK"

[[mods]]
type = "modrinth"
id = "oJBq6bNW"
version = "UybfoNN4"

[[mods]]
type = "modrinth"
id = "Orvt0mRa"
version = "yTh7W27h"

[[mods]]
type = "modrinth"
id = "fQEb0iXm"
version = "jiDwS0W1"

[[mods]]
type = "modrinth"
id = "1IjD5062"
version = "Z9FJWLMt"

[[mods]]
type = "modrinth"
id = "eNF4Bfla"
version = "7cR2Lz0f"

[[mods]]
type = "modrinth"
id = "l6YH9Als"
version = "XGW2fviP"

[[mods]]
type = "modrinth"
id = "YL57xq9U"
version = "URWeWMAt"

[[mods]]
type = "modrinth"
id = "EsAfCjCV"
version = "CxnVG86Y"

[[mods]]
type = "modrinth"
id = "OCxj9VC8"
version = "hlS5XQgk"

[[mods]]
type = "modrinth"
id = "z7dmZ4nL"
version = "gyLsjEk8"

[[mods]]
type = "modrinth"
id = "iG6ZHsUV"
version = "mafk58Fm"

[[mods]]
type = "modrinth"
id = "j2HhbEE7"
version = "kWMqVWTm"

[[mods]]
type = "modrinth"
id = "siXFh9dn"
version = "ZKDQu5sd"

[[mods]]
type = "modrinth"
id = "fThnVRli"
version = "oSyOLHYj"

[[mods]]
type = "modrinth"
id = "P0Mu4wcQ"
version = "bbR3MLn5"

[[mods]]
type = "modrinth"
id = "fPetb5Kh"
version = "NovIXDxY"

[[mods]]
type = "modrinth"
id = "Q2OqKxDG"
version = "MoIoigS0"

[[mods]]
type = "modrinth"
id = "p7ksDUGo"
version = "57bbKX1c"

[[mods]]
type = "modrinth"
id = "nmDcB62a"
version = "1FrMon6Q"

[[mods]]
type = "modrinth"
id = "lhGA9TYQ"
version = "Sbew3kXe"

[[mods]]
type = "modrinth"
id = "qvIfYCYJ"
version = "vTQynnGn"

[[mods]]
type = "modrinth"
id = "1eAoo2KR"
version = "3hsIB5yP"

[[mods]]
type = "modrinth"
id = "hBVVhStr"
version = "xa1QAtHc"

[[mods]]
type = "modrinth"
id = "ZzjhlDgM"
version = "vVIvVuGn"

[[mods]]
type = "modrinth"
id = "sGmHWmeL"
version = "LGYOH4RN"

[[mods]]
type = "modrinth"
id = "nvQzSEkH"
version = "QhvPNPdp"

[[mods]]
type = "modrinth"
id = "705gWllI"
version = "BslzSzGd"

[[mods]]
type = "modrinth"
id = "EV5wjtvP"
version = "E6M1VHCx"

[[mods]]
type = "modrinth"
id = "yBW8D80W"
version = "mYl4RvKg"

[[mods]]
type = "modrinth"
id = "RLrPqrNI"
version = "Rt34JLkK"

[[mods]]
type = "modrinth"
id = "r0v8vy1s"
version = "zrRsTCOk"

[[mods]]
type = "modrinth"
id = "6gLXkYZq"
version = "cLUupLck"

[[mods]]
type = "modrinth"
id = "mOgUt4GM"
version = "lEkperf6"

[[mods]]
type = "modrinth"
id = "OVuFYfre"
version = "i3v1Skck"

[[mods]]
type = "modrinth"
id = "gvQqBUqZ"
version = "ZSNsJrPI"

[[mods]]
type = "modrinth"
id = "uXXizFIs"
version = "unerR5MN"

[[mods]]
type = "modrinth"
id = "wnEe9KBa"
version = "sV8lIBhJ"

[[mods]]
type = "modrinth"
id = "rcLriA4v"
version = "HuXAp0GB"

[[mods]]
type = "modrinth"
id = "cloth-config"
version = "11.1.118+fabric"

[[mods]]
type = "modrinth"
id = "invmove"
version = "1.20-0.8.4-quilt"

[[mods]]
type = "modrinth"
id = "kibe"
version = "1.10.1-BETA+1.20"

[[mods]]
type = "modrinth"
id = "coxinha-utilities"
version = "1.4.13+1.20.1"

[[mods]]
type = "modrinth"
id = "plushables"
version = "1.1.3"

[[mods]]
type = "modrinth"
id = "styled-chat"
version = "2.2.3+1.20.1"

[[mods]]
type = "modrinth"
id = "styled-nicknames"
version = "1.2.1+1.20"

[[mods]]
type = "modrinth"
id = "noexpensive"
version = "3qgbHvhi"

[[mods]]
type = "modrinth"
id = "borderless-mining"
version = "lhrW53q7"

[[mods]]
type = "modrinth"
id = "led"
version = "ax1Oy3Bj"

[[mods]]
type = "modrinth"
id = "scarves"
version = "9kVf8i4b"

[[mods]]
type = "modrinth"
id = "jar-jar-binks"
version = "4mwjl1tb"

[[mods]]
type = "modrinth"
id = "only-hammers-and-excavators"
version = "Y4RlTy67"

[[mods]]
type = "modrinth"
id = "wyd"
version = "ph5bnMLH"

[[mods]]
type = "modrinth"
id = "botania"
version = "s3EM29A3"

[[mods]]
type = "modrinth"
id = "automobility"
version = "G97BY8OB"

[[mods]]
type = "modrinth"
id = "qkl"
version = "RYTef2Wb"

[[mods]]
type = "modrinth"
id = "patchouli"
version = "Y6tuH1cn"

[[mods]]
type = "modrinth"
id = "azurelib"
version = "qmNj5M34"

[[mods]]
type = "modrinth"
id = "geckolib"
version = "4.2.2"

[[mods]]
type = "modrinth"
id = "mctitlechanger"
version = "1.10.2"

[[mods]]
type = "modrinth"
id = "axes-are-weapons"
version = "1.7.3-fabric-1.20.2"

[[mods]]
type = "modrinth"
id = "polymorph"
version = "GcFD377O"

[[mods]]
type = "modrinth"
id = "expanded-storage"
version = "10.1.1+fabric"

[[mods]]
type = "modrinth"
id = "chex-mix-mod"
version = "HCqhjZSr"

[[mods]]
type = "modrinth"
id = "chat-heads"
version = "N6Cgb8gp"

[[mods]]
type = "modrinth"
id = "no-shield-delay"
version = "1.0.0"

[[mods]]
type = "modrinth"
id = "blahaj"
version = "0.3.0+1.20.1"

[[mods]]
type = "modrinth"
id = "simple-voice-chat"
version = "fabric-1.20.1-2.4.32"

[[mods]]
type = "modrinth"
id = "voice-chat-interaction"
version = "fabric-1.20.1-1.0.6"

[[mods]]
type = "modrinth"
id = "arch-ex"
version = "quIy1Qya"

[[mods]]
type = "modrinth"
id = "creeper-overhaul"
version = "dVCs4doR"

[[mods]]
type = "modrinth"
id = "fabric-seasons"
version = "uMEzKato"

[[mods]]
type = "modrinth"
id = "resourceful-config"
version = "PlEObkl9"

[[mods]]
type = "modrinth"
id = "ad-astra"
version = "QzjRLT8e"

[[mods]]
type = "modrinth"
id = "dark-enchanting"
version = "FrLkTZon"

[[mods]]
type = "modrinth"
id = "resourceful-lib"
version = "HGTwQLNx"

[[mods]]
type = "modrinth"
id = "botarium"
version = "a6dUCytc"

[[mods]]
type = "modrinth"
id = "spelunkery"
version = "jkZktG9C"

[[mods]]
type = "modrinth"
id = "templates-2"
version = "2.1.1-fabric-1.20.1"

[[mods]]
type = "modrinth"
id = "vivecraft"
version = "1.20.1-1.1.5-fabric"

[[mods]]
type = "modrinth"
id = "ping-wheel"
version = "Y8dEw4Lk"

[[mods]]
type = "modrinth"
id = "adorn"
version = "5.0.1-fabric"

[[mods]]
type = "modrinth"
id = "bounced"
version = "3.1.1-mc1.20"

[[mods]]
type = "modrinth"
id = "friends-and-foes"
version = "fabric-mc1.20.1-2.0.7"

[[mods]]
type = "modrinth"
id = "friends-and-foes-flowery-mooblooms-fabric"
version = "fabric-mc1.20.1-2.0.0"

[[mods]]
type = "modrinth"
id = "diagonal-fences"
version = "v8.1.3-1.20.1-Fabric"

[[mods]]
type = "modrinth"
id = "puzzles-lib"
version = "v8.1.13-1.20.1-Fabric"

[[mods]]
type = "modrinth"
id = "carpeted-stairs"
version = "1.20-1.4"

[[mods]]
type = "modrinth"
id = "moonlight"
version = "fabric_1.20-2.8.82"

[[mods]]
type = "modrinth"
id = "softer-pastels"
version = "0.4.0"

[[mods]]
type = "modrinth"
id = "dark-utilities"
version = "17.0.3"

[[mods]]
type = "modrinth"
id = "bookshelf-lib"
version = "20.1.8"

[[mods]]
type = "modrinth"
id = "better-ladders"
version = "vhz0me3l"

[[mods]]
type = "modrinth"
id = "redstonepen"
version = "1.5.24"

[[mods]]
type = "modrinth"
id = "pearfection"
version = "1.1.1"

[[mods]]
type = "modrinth"
id = "do-a-barrel-roll"
version = "3.3.8+1.20-fabric"

[[mods]]
type = "modrinth"
id = "bits-and-chisels"
version = "2.7.3"

[[mods]]
type = "modrinth"
id = "universal-graves"
version = "3.0.0+1.20.1"

[[mods]]
type = "modrinth"
id = "not-enough-animations"
version = "lODpunva"

[[mods]]
type = "modrinth"
id = "inmis"
version = "2.7.2+1.20.1"

[markdown]
files = ["README.md"]
auto_update = true

[options]
