name = "season-6-modpack"
version = "52c58bf5f0bb941fb62cd3aa3cf6a2f7714d7b3f"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "dabae69582bff0e9e69de7f0739c350feb1e173196d45c0649012a31ecdaaa0c"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
quilt = "0.23.0"
minecraft = "1.20.1"
