name = "season-6-modpack"
version = "b06f85f6f0a55150de93cacc5990922e908d55b2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "be03e4f3fb468651774bb3ccc8aaf377b2fbb6e5dbc2d81afa3324ab3613988f"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
quilt = "0.23.0-beta.1"
minecraft = "1.20.1"
