name = "season-6-modpack"
version = "8d12932dd8dcad5ffef1e4d02b918b3c1f892c25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "0840cd61ec4ec388769b0d11ce3e7879583d17fb519d9abdb5fab1f2b9d4e5af"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.1"
quilt = "0.23.0-beta.1"
