name = "season-6-modpack"
version = "d5eb191feec6ac5b7c1b7a3efef255bb6cecb832"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "6e54553bcb44869b1b6e4f3fcccebb2b9f6b34c091017cded27a76ba6be2e948"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.1"
quilt = "0.23.0-beta.1"
