name = "season-6-modpack"
version = "19d11af32d23f959b4a21fe3a1c8990f97675d4f"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "af899808af6fc93d3530dd067b3ae6d209bc99fc1ee51972e8aea93ba80c5826"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.1"
quilt = "0.23.0-beta.1"
