name = "season-6-modpack"
version = "a843ef26c23d78b5e426edb41518d6ded741b6cb"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "4725fb2574ae4c430afdffd2af71be3875b46580802c271277b77c26dfabd4a0"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
quilt = "0.23.0"
minecraft = "1.20.1"
