name = "season-6-modpack"
version = "544d2bd995327c46fb3d25bb59be926fc6b5fe12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "c7fd6cbe5eaa63bd96d7bc6061457abd0ccaed6984611f788e5d23ec7ab6fa6a"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
quilt = "0.23.0-beta.1"
minecraft = "1.20.1"
