name = "season-6-modpack"
version = "11408587df8c3ae1cef82100697dadf8ae5b42ed"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "e895ec1bca90b3a118d43bf52d51b93b33fabd066900538699c6157ef55fd3e2"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
