name = "season-6-modpack"
version = "25a059bb39ee5babcb945a45bfd7a2fc2b395c30"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "ae628b82f7bf728b92b34b20db37f220a7ded927db6d9ea293ad8b5fefbc9fd9"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.1"
quilt = "0.23.0-beta.1"
