name = "season-6-modpack"
version = "d262f38cccf291cf87c7c000ecd4f1cabeb093e9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "d3a848b709f25aef566af5aa6142ac45c95a6794636e4bc94d36893d16f3be56"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
quilt = "0.23.0"
minecraft = "1.20.1"
