name = "season-6-modpack"
version = "17ffff6bbc3633f0bef7926d85aeebb531edcfe7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "40c11dce0efd64a9b31c174b858153cfaf01b752e396a2db24ad1a1aed4b559c"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
