name = "season-6-modpack"
version = "ca08ac9860ea9ea9390695fe7563e2efa1cedb85"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "2956e23974f2a2791c496c297846dd32fbbfc01d8fe7dcbd591072d179cb2b53"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
quilt = "0.23.0"
minecraft = "1.20.1"
