name = "season-6-modpack"
version = "5a04f86ccf2a73199ffc9b3ea1d24cc47089c38b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "d3a848b709f25aef566af5aa6142ac45c95a6794636e4bc94d36893d16f3be56"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
