name = "season-6-modpack"
version = "47aa547eaf769b62694a4aca90b96e3626d9d402"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "e9ebcf5f06f2df145c1460c8ac7132762d1d6ba0fe596da62b24b7e6e71dc12b"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
