name = "season-6-modpack"
version = "20efbd860bd49f42c9483fb7b9866739a599dad6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "bc62c91a596ca6dad043f29a4a3b042bbc1e967ea4d930d91e2dd1893366a69f"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
