name = "season-6-modpack"
version = "00ecf317e059fc7380c4affbe725dfd611cad1da"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "6c3cd452b5b24d6702213a3ae47aedc32bc7d47f95c87ffc01a44e11f2e9f230"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
quilt = "0.23.0"
minecraft = "1.20.1"
